version: '3'
services: 
  node-red:
    image: nodered/node-red:latest
    environment: 
      - TZ=America/New_York
    ports:
      - "1880:1880"
    networks:
      - happy-net
    volumes:
      - node-red-data:/data
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    networks:
      - happy-net
    volumes:
      - mosquitto-data:/mosquitto/data
  influxdb:
    image: influxdb:1.8-alpine
    ports:
      - "8086:8086"
    networks:
      - happy-net
    volumes: 
      - influxdb-data:/var/lib/influxdb
  grafana:
    image: grafana/grafana
    environment: 
      - GF_AUTH_ANONYMOUS_ENABLED=true
    ports:
      - "3000:3000"
    networks:
      - happy-net
    volumes: 
      - grafana-data:/var/lib/grafana

volumes:
  node-red-data:
  mosquitto-data:
  influxdb-data:
  grafana-data:

networks:
  happy-net:
